/** Daily sonography tips. HTML allowed (bold/emphasis). Index cycles by day. */
export const SONO_TIPS: string[] = [
  // ── Vascular ───────────────────────────────────────────────────────────────
  `The "superficial" femoral vein is part of the <b>deep</b> venous system — DVT here still requires anticoagulation. Never let the name mislead you or your provider.`,
  `Always angle-correct to <b>60° or less</b> for spectral Doppler velocity measurements. Angles above 60° introduce significant error and can falsely elevate or lower your PSV.`,
  `A monophasic waveform in a lower extremity artery suggests proximal obstruction. Always scan proximally — the problem is upstream.`,
  `When you see reversed flow in the <b>vertebral artery</b>, think subclavian steal. Ask if the patient has arm claudication or dizziness with arm exercise.`,
  `Color Doppler aliasing isn't always bad — it can help you quickly locate the jet of a stenosis. Use it to your advantage before switching to spectral.`,
  `The <b>ICA has no branches</b> in the neck. If you see branches, you're looking at the ECA. Tap the superficial temporal artery to confirm — ECA waveform will bounce.`,
  `For DVT compression, if the vein doesn't fully collapse with gentle pressure, that's abnormal. You shouldn't need to press hard — excessive force compresses the artery too and gives a false sense of security.`,
  `Waveform morphology tells a story: <b>triphasic = normal</b>, biphasic = mild disease, monophasic = significant proximal obstruction or high-resistance state.`,
  `When mapping veins for fistula creation, always document diameter, depth, and compressibility. A vein <b>≥ 2.5 mm</b> at rest (≥ 3.5 mm with tourniquet) is the general threshold for maturation potential.`,
  `An ABI > <b>1.3</b> is non-compressible and unreliable — calcified vessels in diabetics and renal disease patients won't compress. Consider toe pressures instead.`,
  `For AVF surveillance, a PSV ratio > <b>3.0</b> across a stenosis or brachial artery flow < 500 mL/min suggests significant stenosis needing referral.`,
  `When evaluating carotid stenosis, PSV alone isn't enough. Always use the <b>ICA/CCA PSV ratio</b> — a ratio > 4 suggests ≥ 70% stenosis even if PSV seems borderline.`,
  `The popliteal vein runs <b>superficial</b> to the popliteal artery — remember "VAIN" (vein is anterior/superficial in the popliteal fossa). This reverses from the thigh.`,
  `Normal peak systolic velocity in the <b>CCA</b> is 60–100 cm/s. Velocities below 40 cm/s may indicate low cardiac output or proximal disease, not just technique.`,
  `When scanning the IVC for volume status, a diameter <b>< 2.1 cm</b> that collapses > 50% with inspiration suggests low right atrial pressure (< 5 mmHg).`,
  `The <b>peroneal artery</b> is the hardest to find in a three-vessel runoff. It runs deep between the tibia and fibula — start at the mid-calf and follow it distally.`,
  `Chronic DVT looks different: the vein is thick-walled, echogenic, may not compress, and often has collaterals. Don't call it acute without fresh, anechoic thrombus.`,
  `For upper extremity DVT, <b>subclavian and axillary veins</b> require Valsalva maneuver augmentation since compression is not possible over the clavicle.`,
  `Mid-systolic deceleration in the <b>ICA waveform</b> (the "notch") can indicate downstream resistance increase — think high-grade distal stenosis or occlusion.`,
  `An end-diastolic velocity > <b>100 cm/s</b> in the ICA almost always means ≥ 70% stenosis regardless of PSV. EDV is underappreciated in carotid work.`,
  `The <b>brachial artery</b> waveform should be triphasic. A biphasic or monophasic brachial waveform in an ABI study suggests inflow disease proximal to the measurement site.`,
  `Gastrocnemius veins are <b>not part of the deep system</b> — DVT there is lower risk than in axial veins. Know your lab's protocol; many do not anticoagulate for isolated calf muscle vein thrombus.`,
  `On carotid duplex, always document the <b>plaque composition</b>: echogenic (calcified), echolucent (lipid-rich), heterogeneous. Echolucent plaques carry higher stroke risk.`,
  `The <b>proximal SFA</b> is the most common site for atherosclerosis in the lower extremity. If you find disease here, look carefully at the Hunter's canal (mid-thigh) too.`,
  `Venous reflux is defined as flow reversal lasting <b>> 0.5 seconds</b> in superficial veins and > 1.0 second in the deep system after augmentation release.`,
  `Never forget the <b>profunda femoris</b> (deep femoral artery) — it's a major collateral in SFA occlusion. Document its origin and flow direction.`,
  `The normal portal vein velocity is <b>15–25 cm/s</b>. Below 10 cm/s raises concern for portal hypertension; above 30 cm/s can occur with arteriovenous fistula.`,
  `When performing a lower extremity venous exam, always start at the <b>common femoral vein</b> — this is the gateway. If it's occluded, everything distal may appear compressed but be falsely so.`,
  `Renal artery stenosis: a PSV > <b>180–200 cm/s</b> at the origin or a RAR (renal-to-aortic ratio) > 3.5 are the primary duplex criteria for hemodynamically significant stenosis.`,
  `The <b>tardus-parvus</b> waveform (slow rise, rounded peak, low velocity) distal to a stenosis is a reliable indirect sign of significant proximal obstruction.`,
  `In a hemodialysis graft, flow should travel from <b>artery → graft → vein</b>. Reversed flow in the venous limb suggests steal or graft dysfunction.`,
  `Document the <b>ankle brachial index</b> as a ratio, not just the pressure. Normal is 0.9–1.3. Claudication is typically 0.5–0.9, rest pain < 0.5, tissue loss < 0.3.`,

  // ── Abdominal / General ────────────────────────────────────────────────────
  `The <b>right renal artery</b> passes behind the IVC — use the IVC as a window. Angle slightly posterior and you'll find it without needing a flank approach.`,
  `A RI > <b>0.70</b> in the renal arteries suggests increased parenchymal resistance. Think hydronephrosis, rejection (transplant), or medical renal disease.`,
  `Bowel gas is your enemy. Have patients fast for abdominal aorta and mesenteric scans, and try gentle graded compression to displace gas. Patience and position changes work.`,
  `The <b>celiac axis</b> has a classic "seagull" appearance in transverse — two wings spreading left (splenic) and right (hepatic). Once you see it, you'll never forget it.`,
  `SMA waveform is normally <b>high resistance</b> fasting and low resistance postprandial. A fasting SMA that looks low resistance may indicate bowel ischemia or AVM.`,
  `Doppler of the <b>portal vein</b> should show hepatopetal (toward liver) flow. Hepatofugal (away) flow is a red flag for portal hypertension — document and alert the reading physician immediately.`,
  `A normal aorta tapers gradually. Any segment that looks <b>larger than the one above it</b> should raise suspicion. Measure outer wall to outer wall in the true AP diameter.`,
  `When measuring the AAA, always get both AP and transverse. AP is the hemodynamically important diameter — transverse alone can underestimate due to tortuous vessels.`,
  `The gallbladder wall should measure <b>< 3 mm</b> in a fasted, distended gallbladder. Causes of wall thickening beyond cholecystitis include CHF, hepatitis, hypoalbuminemia, and ascites.`,
  `Murphy's sign on ultrasound: maximum tenderness directly under the probe over the gallbladder. A positive sonographic Murphy's with gallstones has high specificity for acute cholecystitis.`,
  `Common bile duct diameter: <b>< 6 mm</b> is normal. Add 1 mm per decade after age 60. Post-cholecystectomy patients can have up to 10 mm without obstruction.`,
  `The <b>pancreas</b> is retroperitoneal. Use the SMA and SMV as landmarks — the body of the pancreas crosses anterior to them. The splenic vein runs along the posterior pancreas.`,
  `A spleen > <b>13 cm</b> in long axis is considered splenomegaly. Causes include portal hypertension, hematologic disorders, and infections. Always measure on the longest axis.`,
  `The <b>Morrison's pouch</b> (hepatorenal space) is the most dependent part of the peritoneal cavity in a supine patient — it's the first place free fluid collects. Check it on every abdominal study.`,
  `Echogenic liver + posterior attenuation = fatty infiltration. But <b>focal fatty sparing</b> near the gallbladder fossa and porta hepatis can mimic a mass — don't miss it.`,
  `Normal kidney length is <b>9–12 cm</b>. A kidney < 9 cm may indicate chronic disease. Asymmetry > 2 cm between kidneys warrants further evaluation.`,
  `Hydronephrosis grading: mild (pelvis dilated), moderate (calyces dilated), severe (cortical thinning). <b>Always check the bladder</b> — an overdistended bladder can cause false-positive mild hydronephrosis.`,
  `The <b>hepatic veins</b> drain into the IVC at nearly a right angle. Dilatation of hepatic veins + IVC suggests right heart failure or Budd-Chiari syndrome.`,
  `For renal transplant surveillance, resistive indices > <b>0.80</b> are concerning. But always correlate — pain, fever, and clinical context matter more than any single number.`,
  `An adrenal mass found incidentally is called an <b>incidentaloma</b>. Ultrasound is poor for characterizing adrenal lesions — document the finding and recommend CT or MRI.`,
  `The <b>caudate lobe</b> of the liver (segment 1) enlarges in Budd-Chiari syndrome because it has separate venous drainage directly into the IVC.`,
  `When you see ascites, always look for <b>septations and echogenicity</b>. Simple anechoic fluid = transudate. Complex, echogenic, or loculated fluid = exudate, blood, or malignancy.`,
  `Use the <b>intercostal approach</b> for the right lobe of the liver when subcostal access is limited. Have the patient hold their breath — it drops the liver right into view.`,
  `A thickened, edematous bowel wall with loss of normal stratification is a red flag. Normal bowel wall is <b>< 3–4 mm</b> when compressed. Thickening suggests ischemia, inflammation, or malignancy.`,
  `The <b>pancreatic duct</b> should measure < 3 mm in diameter. Dilation > 3 mm without a clear cause needs further evaluation — think obstructing mass at the head.`,

  // ── OB / GYN ───────────────────────────────────────────────────────────────
  `Crown-rump length (CRL) is the <b>most accurate</b> dating measurement — use it before 14 weeks whenever possible. After 22 weeks, biometry dating windows widen significantly.`,
  `When you can't find the fetal heartbeat, don't panic the patient. Try the <b>TV probe</b> or wait a few minutes and recheck. Document what you see, not what you assume.`,
  `A CRL of <b>7 mm or more</b> without a visible heartbeat on transvaginal ultrasound is suspicious for failed pregnancy. A second scan 7–10 days later confirms — never diagnose on one scan alone.`,
  `The <b>yolk sac</b> appears before the embryo and should be visible by 5.5 weeks TV. A yolk sac without an embryo may mean you're early — correlate with hCG and rescan.`,
  `Placenta previa diagnosis should always be confirmed with <b>transvaginal ultrasound</b>. Transabdominal images are unreliable for the lower uterine segment — bladder filling causes false positives.`,
  `The four-chamber view isn't enough for cardiac screening — add the <b>LVOT and RVOT views</b>. Most conotruncal defects (TOF, TGA) won't be caught on four-chamber alone.`,
  `Umbilical cord should have <b>2 arteries and 1 vein</b>. A single umbilical artery (SUA) is associated with structural and chromosomal anomalies — always document and flag it.`,
  `AFI and single deepest pocket both have roles. <b>SDP ≥ 2 cm</b> is the threshold for normal. If it's borderline, note it and correlate clinically — fluid levels fluctuate.`,
  `Nuchal translucency measurement should be performed between <b>11–14 weeks</b> with CRL 45–84 mm. The NT should be < 3 mm; above that warrants genetic counseling.`,
  `Fetal gender: the <b>"angle sign"</b> at 11–13 weeks — genital tubercle angled > 30° from spine = male, < 30° = female. Don't guess before 14 weeks; you'll be wrong more than you think.`,
  `The <b>cisterna magna</b> should measure 2–10 mm in the posterior fossa. Enlargement > 10 mm may indicate Dandy-Walker variant or other posterior fossa anomalies.`,
  `Normal fetal kidneys are slightly hyperechoic relative to the liver in the second trimester. By the third trimester, they become more isoechoic. <b>Hyperechoic kidneys</b> in the third trimester are abnormal.`,
  `Always measure the <b>cervical length</b> transvaginally when short cervix is suspected. Normal is > 25 mm at 16–24 weeks. < 20 mm at any gestational age is concerning for preterm risk.`,
  `The umbilical artery Doppler should show <b>forward end-diastolic flow</b>. Absent or reversed end-diastolic flow is a critical finding indicating severe uteroplacental insufficiency.`,
  `Vasa previa: fetal vessels crossing the internal os. Look for this when there's a <b>velamentous cord insertion</b> or succenturiate lobe. It's rare but can be fatal if missed.`,
  `Normal fetal stomach should be visible as a <b>fluid-filled structure</b> in the left upper quadrant by 14 weeks. Absent stomach may indicate esophageal atresia, oligohydramnios, or a swallowing problem.`,
  `The <b>choroid plexus</b> occupies most of the lateral ventricles in the second trimester and should appear bright and symmetric. Choroid plexus cysts alone are not significant if anatomy is otherwise normal.`,
  `Measure the <b>lateral ventricle atrium</b> at the level of the glomus of the choroid plexus. Normal is < 10 mm. 10–15 mm = mild ventriculomegaly; > 15 mm = severe.`,
  `For ovarian torsion, the <b>absence of Doppler flow</b> is not required — torsion can be intermittent and flow may still be present. Clinical suspicion + enlarged ovary + follicles = surgical emergency.`,
  `A complex adnexal mass in a reproductive-age woman with a positive pregnancy test = <b>ectopic until proven otherwise</b>. A gestational sac in the uterus effectively excludes ectopic (except in IVF patients).`,
  `The <b>endometrial stripe</b> should be < 4–5 mm in postmenopausal women not on HRT. Anything thicker warrants endometrial sampling regardless of bleeding status.`,
  `Measure ovarian volume using the ellipsoid formula: <b>L × W × H × 0.523</b>. Normal premenopausal volume is < 10 mL; postmenopausal < 8 mL. Larger volumes need follow-up.`,
  `The Doppler RI of the <b>uterine artery</b> normally decreases as pregnancy progresses. Persistently high RI or notching at 20–24 weeks is associated with preeclampsia risk.`,
  `A Nabothian cyst on the cervix is a benign retention cyst. Do not confuse it with a <b>nabothian cyst vs endocervical polyp</b> — polyps are vascular on Doppler, cysts are not.`,
  `For a fetal anatomy survey, always include <b>face, lips, and palate</b>. Cleft lip is visible on ultrasound; cleft palate alone is harder to detect. Document what you can see.`,
  `<b>Subchorionic hematoma</b> appears as a hypoechoic or anechoic crescent between the chorion and the uterine wall. Large hematomas (> 25% of sac volume) carry higher miscarriage risk.`,
  `When scanning a bicornuate or septate uterus, <b>3D ultrasound</b> is the best way to differentiate — but on 2D, the fundal contour is key. Bicornuate has a concave fundus; septate has a convex one.`,
  `The <b>fetal profile</b> view assesses the nose, lips, chin, and forehead. A flat nasal bone at 11–14 weeks is associated with trisomy 21 — always try to document it at the first-trimester screen.`,
  `During a fetal echo, use the <b>3-vessel view</b> (MPA, aorta, SVC) to assess size, alignment, and number of vessels. A missing or extra vessel changes the differential significantly.`,
  `Placental location matters throughout pregnancy. Document <b>anterior, posterior, fundal, or low-lying</b> at every scan. An anterior placenta affects amniocentesis planning and delivery approach.`,
  `In suspected placenta accreta spectrum, look for loss of the <b>clear space</b> (hypoechoic zone) between placenta and myometrium, placental lacunae, and bladder wall irregularity.`,
  `The <b>fetal spine</b> should be evaluated in sagittal, transverse, and coronal planes. Open spina bifida causes the "lemon" and "banana" signs in the fetal head at the 18–20 week scan.`,

  // ── Thyroid & Small Parts ──────────────────────────────────────────────────
  `TI-RADS isn't just about size — it's about <b>composition, echogenicity, shape, margin, and echogenic foci</b>. A 5 mm nodule can be TR5 if it has all the right features.`,
  `Taller-than-wide orientation (anteroposterior > transverse on transverse image) is the single <b>most suspicious</b> TI-RADS feature. Don't skip measuring both axes.`,
  `Comet-tail artifacts in thyroid nodules suggest benign colloid — they're different from microcalcifications. <b>True microcalcs are punctate and non-shadowing.</b>`,
  `Document the parathyroid region whenever you're doing a thyroid scan. An enlarged hypoechoic oval structure posterior to the thyroid lobe on spectral may represent a parathyroid adenoma.`,
  `Thyroid volume formula: <b>L × W × H × 0.523</b> for each lobe. Normal total volume is < 10 mL in women and < 25 mL in men. Document both lobes plus the isthmus.`,
  `Hashimoto's thyroiditis: diffuse heterogeneous echotexture, increased vascularity, and a <b>micronodular</b> pattern. The gland is often enlarged early and atrophic late in disease.`,
  `In Graves' disease, expect a <b>"thyroid inferno"</b> — markedly increased vascularity on color Doppler throughout both lobes. This differentiates it from subacute thyroiditis, which is hypovascular.`,
  `Isthmus thickness: measure anterior to posterior. Normal is <b>< 5 mm</b>. An isthmus > 5 mm can harbor nodules and should be measured and documented separately.`,
  `Lymph nodes in the neck: look for a <b>fatty hilum</b> as a sign of benign morphology. Loss of the hilum, rounded shape, and increased peripheral vascularity suggest malignancy.`,
  `A salivary gland stone (sialolith) appears as a <b>hyperechoic focus with posterior shadowing</b> within the duct. The submandibular gland and Wharton's duct are the most common sites.`,
  `Normal parotid gland is homogeneous and slightly hyperechoic compared to muscle. Heterogeneity, cysts, or hypoechoic areas in the parotid warrant further evaluation.`,
  `When scanning a neck mass, always ask: is it <b>cystic, solid, or complex</b>? A branchial cleft cyst is typically a thin-walled anechoic structure near the anterior border of the SCM.`,
  `The <b>isthmus of the thyroid</b> overlies the trachea. The trachea creates a posterior acoustic shadow — don't mistake this for a pathologic finding.`,
  `Thyroid nodule vascularity pattern: peripheral vascularity is common in benign nodules; <b>central chaotic vascularity</b> is more associated with malignancy. Neither is definitive alone.`,
  `Always measure thyroid nodules in <b>three dimensions</b> on the same image plane. Longitudinal diameter, transverse diameter, and AP diameter — then calculate volume with the ellipsoid formula.`,
  `Reactive lymph nodes are oval, hypoechoic, and maintain a <b>fatty hilum</b>. If the node is round (short-to-long axis ratio > 0.5) or has lost the hilum, it's suspicious.`,
  `The <b>recurrent laryngeal nerve</b> runs in the tracheoesophageal groove — document any suspicious thyroid tissue in this region, as disease here affects surgical planning.`,

  // ── Cardiac / Echo ─────────────────────────────────────────────────────────
  `In echo, <b>subcostal views</b> are your friend when parasternal and apical windows are poor — common in COPD, obesity, and post-op patients. Always try it before giving up on windows.`,
  `A pericardial effusion can look dramatic but be hemodynamically insignificant. Look for <b>RA/RV diastolic collapse</b> and IVC plethora to suggest tamponade physiology.`,
  `Doppler of the <b>mitral inflow</b>: E/A ratio < 1 in a patient > 50 suggests diastolic dysfunction. But don't over-diagnose — always integrate with tissue Doppler and clinical context.`,
  `When measuring EF by eye (visual estimation), studies show experienced sonographers are within 5–10% of quantitative methods. Trust your eye but always document biplane if the clinical question matters.`,
  `The <b>aortic valve</b> should open fully in systole. Restricted opening with increased velocity (> 4 m/s = severe AS) indicates significant stenosis. Measure the jet from the apical 5-chamber or 3-chamber view.`,
  `The <b>tricuspid regurgitation jet</b> velocity lets you estimate RVSP: use 4V² + RAP. A TR jet > 2.8 m/s suggests pulmonary hypertension and should be flagged.`,
  `Mitral valve prolapse: the leaflet(s) bow back into the LA > <b>2 mm</b> beyond the annular plane in the parasternal long-axis view. The apical view is unreliable for MVP diagnosis due to saddle shape.`,
  `Normal aortic root diameter at the sinuses of Valsalva is <b>≤ 3.7 cm in women</b> and <b>≤ 4.0 cm in men</b>. Values above this need surveillance; > 5.5 cm typically triggers surgical consideration.`,
  `The <b>TAPSE</b> (tricuspid annular plane systolic excursion) is a simple measure of RV function. Measure M-mode at the lateral tricuspid annulus. Normal is > 17 mm; < 17 mm indicates RV dysfunction.`,
  `On tissue Doppler, the <b>e' velocity</b> at the medial mitral annulus should be ≥ 7 cm/s and lateral ≥ 10 cm/s. Below these values confirms diastolic dysfunction even with normal E/A.`,
  `A dilated, poorly contracting RV with a D-shaped LV (flattened interventricular septum) in short-axis is the hallmark of <b>right heart pressure overload</b> — think PE or pulmonary hypertension.`,
  `The <b>parasternal short-axis</b> at the mitral valve level shows the "fish mouth" opening of the MV. Restricted opening, doming, and commissural fusion = mitral stenosis.`,
  `Hypertrophic cardiomyopathy: asymmetric septal hypertrophy with a <b>septal-to-posterior wall ratio > 1.3</b> and systolic anterior motion (SAM) of the mitral valve causing LVOT obstruction.`,
  `When you see a mass in the left atrium near the atrial septum, think <b>myxoma</b>. It's typically a mobile, pedunculated, gelatinous mass attached to the fossa ovalis. Always document mobility.`,
  `The <b>inferior vena cava</b> is your best non-invasive window into right atrial pressure. IVC > 2.1 cm that collapses < 50% with inspiration = elevated RAP (≥ 10 mmHg).`,
  `Aortic regurgitation severity: look for <b>pressure half-time</b> on CW Doppler — < 200 ms = severe AR. Also document LV size (dilated = chronic, normal = acute) and diastolic flow reversal in the descending aorta.`,

  // ── MSK (Musculoskeletal) ──────────────────────────────────────────────────
  `For shoulder ultrasound, the <b>rotator cuff interval</b> contains the biceps tendon, superior glenohumeral ligament, and coracohumeral ligament. Pathology here is often overlooked.`,
  `Normal tendons appear <b>fibrillar and hyperechoic</b>. Any area of hypoechogenicity within a tendon is abnormal — think tendinosis, partial tear, or full thickness tear.`,
  `The <b>dynamic assessment</b> is the most valuable part of MSK ultrasound. Move the joint while scanning — impingement, subluxation, and snapping syndromes are only visible in motion.`,
  `Anisotropy is the biggest pitfall in MSK ultrasound: tendons look <b>falsely hypoechoic</b> when the beam isn't perpendicular to the fibril orientation. Always heel-toe the probe to correct.`,
  `For a rotator cuff tear, the key finding is loss of the normal convex bursal surface. A <b>full-thickness tear</b> shows absence of tendon substance with direct communication between joint and bursa.`,
  `The <b>carpal tunnel</b> is best evaluated transversely at the pisiform level. Normal median nerve cross-sectional area is < 10–13 mm². Enlargement with flattening distally is carpal tunnel syndrome.`,
  `Plantar fasciitis: the plantar fascia at the calcaneal insertion should be <b>< 4 mm</b>. Thickening > 4–5 mm with hypoechogenicity and loss of fibrillar pattern = fasciitis.`,
  `For Achilles tendon evaluation, the tendon should be uniform and fibrillar throughout. A <b>partial tear</b> shows a focal hypoechoic defect; a full tear shows a gap filled with fluid or echogenic debris.`,
  `Bursae are normally thin, collapsed, non-visualized spaces. A <b>distended bursa</b> appears as an anechoic or hypoechoic fluid collection. Always check for internal vascularity — inflammation vs. infection matters.`,
  `The <b>ulnar nerve</b> at the cubital tunnel is evaluated transversely. Normal cross-sectional area is < 7.5 mm². Enlargement or subluxation with elbow flexion is significant.`,
  `For hip joint effusion, compare both hips. A difference > <b>2 mm</b> in anterior capsule distension is abnormal. Aspirate under ultrasound guidance when infection is suspected.`,
  `When evaluating for a <b>Baker's cyst</b>, look for the neck between the medial gastrocnemius and semimembranosus tendons. Always identify the neck — a mass without a neck needs further evaluation.`,
  `The <b>patellar tendon</b> connects the patella to the tibial tuberosity. Jumper's knee (patellar tendinosis) shows focal thickening and hypoechogenicity at the inferior patellar pole.`,
  `Ganglion cysts are the most common soft tissue masses on MSK ultrasound — anechoic, multilobulated, without internal flow. A ganglion <b>with internal vascularity</b> is not a simple ganglion.`,

  // ── Breast ─────────────────────────────────────────────────────────────────
  `Breast masses should be described by <b>BI-RADS lexicon</b>: shape, orientation, margin, echo pattern, and posterior features. Never make up your own descriptors.`,
  `A simple cyst on ultrasound: <b>anechoic, smooth margins, imperceptible wall, posterior acoustic enhancement</b>. All four criteria must be met. One atypical feature changes it to a complicated cyst.`,
  `<b>Orientation matters</b> in breast ultrasound: parallel (wider than tall) is typically benign. Taller than wide (non-parallel) is suspicious and scores points toward BI-RADS 4.`,
  `Posterior acoustic shadowing in a breast mass suggests <b>desmoplastic reaction</b> — a feature of malignancy. Combined with irregular margins, this is highly suspicious.`,
  `When a palpable lump doesn't correlate with ultrasound findings, scan in the <b>exact position the patient feels it</b> — sitting, standing, or leaning. Gravity changes mass position significantly.`,
  `A complicated cyst has internal echoes, a thickened wall, or septations. Most are benign, but <b>BI-RADS 3</b> is appropriate with short-interval follow-up (6 months).`,
  `The <b>Cooper's ligaments</b> are hyperechoic linear structures connecting the skin to the deep fascia. Disruption or tethering of Cooper's ligaments by a mass is a suspicious finding.`,
  `Axillary lymph node evaluation is part of a complete breast ultrasound. Normal nodes have a <b>fatty hilum and cortex ≤ 3 mm</b>. Cortical thickening > 3 mm or asymmetry warrants documentation.`,
  `Skin thickening > <b>2 mm</b> in the breast (compared to the other side) can indicate inflammatory carcinoma, lymphedema, or radiation changes. Always compare bilaterally.`,
  `When evaluating breast implants, look for <b>"snowstorm" artifact</b> within the implant lumen — this indicates silicone gel bleed (intracapsular rupture). The "linguine sign" = collapsed shell.`,

  // ── Scrotal / Testicular ───────────────────────────────────────────────────
  `Normal testicular echotexture is <b>homogeneous and medium-level echogenicity</b>. Any focal hypoechoic area is suspicious for malignancy until proven otherwise.`,
  `Testicular torsion: the hallmark is <b>absent or decreased intratesticular flow</b> on color Doppler in a painful, enlarged testis. Time is tissue — document and call the urologist immediately.`,
  `The <b>epididymis</b> runs along the posterior-superior aspect of the testis. Epididymo-orchitis shows enlarged, hypervascular epididymis — the opposite pattern from torsion.`,
  `A varicocele: <b>dilated veins > 3 mm</b> in the pampiniform plexus that increase in diameter with Valsalva. Scan with patient upright when possible for best sensitivity.`,
  `A hydrocele is anechoic fluid surrounding the anterolateral testis — benign in isolation. A <b>complex hydrocele</b> (echogenic fluid, septations) raises concern for infection or trauma.`,
  `The <b>mediastinum testis</b> is a normal linear echogenic structure along the posterior testis. Don't mistake it for a mass. It's the entry point for vessels and rete testis.`,
  `Testicular microlithiasis: ≥ 5 echogenic foci < 3 mm per field of view. Current evidence does not mandate biopsy, but <b>annual surveillance</b> ultrasound is recommended given association with germ cell tumors.`,
  `An extratesticular mass is more likely to be benign (epididymal cyst, fibroma) than a testicular mass. Still document carefully — a solid extratesticular mass with vascularity needs follow-up.`,
  `The <b>appendix testis</b> is a small vestigial structure at the superior pole. When it undergoes torsion, it appears as a small hyperechoic or heterogeneous nodule — the "blue dot sign" clinically.`,
  `Always scan <b>both testes</b>, even when the clinical question is unilateral. Bilateral disease (lymphoma, leukemia infiltration) is easy to miss if you only image the symptomatic side.`,

  // ── Physics & Artifacts ────────────────────────────────────────────────────
  `<b>Posterior acoustic enhancement</b> occurs behind fluid-filled structures because fluid attenuates sound less than surrounding tissue. Use it to confirm cystic vs. solid nature.`,
  `<b>Acoustic shadowing</b> appears behind highly reflective structures (calcifications, stones, air). A clean shadow with sharp edges = calcification. Dirty shadow with reverberation = gas.`,
  `The <b>mirror artifact</b> appears behind a strong reflector (like the diaphragm). A liver lesion may appear duplicated above the diaphragm — it's not a second lesion; it's the mirror image.`,
  `<b>Reverberation artifacts</b> (ring-down, comet-tail) repeat at regular intervals deep to a reflective interface. Ring-down is caused by resonating fluid between gas bubbles.`,
  `<b>Harmonic imaging</b> uses the second harmonic frequency generated by tissue. It reduces near-field artifact and improves contrast resolution — turn it on for abdominal and cardiac studies.`,
  `<b>Spatial compounding</b> averages frames from multiple steering angles. It reduces speckle noise and improves margin definition, but can reduce shadowing from gallstones.`,
  `The <b>Doppler angle</b> determines the proportion of true velocity that's measured. At 90°, you measure zero velocity. At 0°, you measure maximum — but positioning is often impractical.`,
  `<b>Aliasing</b> on pulsed wave Doppler occurs when the velocity exceeds the Nyquist limit. Fix it by increasing PRF, shifting baseline, or using CW Doppler for high-velocity jets.`,
  `<b>Range ambiguity</b> occurs when the next pulse is sent before echoes from the previous one return. This causes deep structures to appear in the near field.`,
  `The <b>slice thickness artifact</b> can place echoes inside cysts or vessels, making them look complex. Reduce gain and use a higher frequency probe to minimize this.`,
  `<b>Refraction artifact</b> creates edge shadows at the lateral margins of curved structures (gallbladder, cysts). These are not calcifications — they're due to beam bending at the edge.`,
  `<b>Grating lobes</b> are spurious beams from linear array transducers that can create low-level artifactual echoes. Reduce by lowering gain or using a curved array.`,
  `In color Doppler, a <b>flash artifact</b> is a burst of color caused by patient or probe movement. It's not real flow — always confirm with spectral Doppler before documenting abnormal flow.`,
  `<b>Twinkle artifact</b> is a rapidly changing color signal behind highly reflective objects (calcifications, stones). It's a helpful clue for urinary tract stones even when shadowing is subtle.`,
  `<b>Propagation speed artifact</b> occurs when sound travels through a medium with a different speed than assumed (1540 m/s). Fat, silicone, and foreign bodies can cause apparent displacement of deeper structures.`,

  // ── Knobology & Equipment ─────────────────────────────────────────────────
  `<b>Gain</b> amplifies all returning signals equally. Too much = noisy, too little = dark. Set it so fluid is anechoic and solid tissue has medium-level echogenicity.`,
  `<b>Time gain compensation (TGC)</b> corrects for depth-dependent attenuation. Slide controls should produce uniform brightness from near to far field — not a gradient.`,
  `<b>Frequency selection</b>: higher frequency = better resolution, less penetration. Lower frequency = worse resolution, better penetration. Always start high and go lower if needed.`,
  `<b>Focal zone placement</b> is the most under-used image quality tool. Place the focus at the depth of your region of interest — resolution improves significantly at that depth.`,
  `<b>Depth adjustment</b>: the structure of interest should fill about <b>two-thirds</b> of the screen. Too much depth wastes resolution; too little crops important anatomy.`,
  `<b>Compression (dynamic range)</b> affects contrast. High compression = more shades of gray, softer look. Low compression = more contrast, crisper edges. Adjust based on the clinical question.`,
  `<b>Power Doppler</b> is more sensitive to slow flow than color Doppler but shows no directionality. Use it when you want to detect flow in small or slow vessels (e.g., testicular, thyroid nodule).`,
  `<b>PRF (pulse repetition frequency)</b> controls the scale on color and spectral Doppler. Low PRF detects slow flow but aliases on fast flow. Match it to the vessel you're interrogating.`,
  `<b>Wall filter</b> removes low-frequency noise from vessel wall motion. Set it high for fast vessels, low for detecting slow venous flow. Over-filtering can eliminate real low-velocity signals.`,
  `<b>Color box size and steering</b> affect frame rate and temporal resolution. Keep the color box as small as needed and angle it to maximize color sensitivity in the direction of flow.`,
  `<b>Persistence (frame averaging)</b> smooths the image by averaging multiple frames. High persistence helps in noisy images but reduces temporal resolution — avoid it in cardiac studies.`,
  `Probe selection: <b>linear</b> for superficial structures (vessels, MSK, thyroid, breast), <b>curvilinear</b> for abdomen and OB, <b>phased array</b> for cardiac and small intercostal windows.`,
  `Clean your probe before and after every patient. <b>Gel harbors bacteria</b> — use single-use packets when possible and never double-dip the bottle into used gel.`,
  `Know your machine's <b>measurement calipers</b> — leading edge to leading edge vs. outer edge to outer edge matters. AAA is outer-to-outer; many vascular measurements are inner-to-inner.`,

  // ── Reporting & Documentation ─────────────────────────────────────────────
  `Always compare <b>bilateral findings</b> on vascular exams — a unilaterally elevated PSV or RI is far more meaningful than bilateral elevation, which may reflect a normal variant or technique issue.`,
  `Document your probe position and patient position when findings are subtle. The next sonographer re-scanning the patient needs to reproduce your view, not guess how you got there.`,
  `If your image quality is poor, <b>change something</b> before giving up: patient position, probe position, frequency, harmonic imaging, gain. Never submit a non-diagnostic study without documentation of attempts.`,
  `Write what you <b>see</b>, not what you think it is. "Heterogeneous hypoechoic mass with irregular margins" is your job. "Malignancy" is the radiologist's call.`,
  `When a finding surprises you, <b>scan longer</b>. Artifacts disappear, real findings persist. Real structures have consistent anatomy — artifacts change with probe angle.`,
  `Always document <b>measurements in the correct plane</b>. Length on longitudinal image, width and AP on transverse. Mislabeled measurements create medicolegal risk.`,
  `If you find an unexpected critical finding, don't just save images and move on. Notify your supervisor or radiologist <b>immediately</b>. "I saved the image" is not the same as communicating the finding.`,
  `Use <b>standardized terminology</b> from your society guidelines (ACR, AIUM, SRU). "Echogenic foci" not "bright spots." "Anechoic" not "black." Consistency protects you and the patient.`,
  `Every study should have a <b>technical quality statement</b>. "Limited due to body habitus," "patient unable to cooperate," or "technically adequate" gives the interpreting physician context.`,
  `<b>Document what you didn't see</b> when it's clinically relevant. "No free fluid identified in the right upper quadrant" is as important as documenting what is there.`,
  `When measurements are borderline, get them twice. The average of two measurements is more defensible than one. <b>Reproducibility</b> is a quality metric.`,
  `Before finalizing a study, scroll through all your images. Ask: "Would a radiologist who wasn't in the room understand what I found and how I found it?" If not, add a clip or label.`,
  `<b>Cine clips</b> are more powerful than static images for dynamic findings: valve motion, DVT compression, peristalsis, fetal heart motion. Save them liberally.`,
  `Date, time, and laterality markers must be correct on every image. Wrong side on a breast biopsy or wrong date on a follow-up study causes real patient harm.`,
  `When measuring a mass, the <b>longest dimension</b> is usually the most clinically relevant for follow-up. Document all three axes, but highlight the maximum dimension in your report.`,

  // ── Clinical Pearls ────────────────────────────────────────────────────────
  `A patient in pain is a moving patient. <b>Build rapport first</b> — explain what you're doing before you press. Patients who trust you move less and breathe better.`,
  `If the patient is NPO and you need a better window, a small sip of water can help fill the stomach to create an acoustic window for the pancreas without significantly affecting the study.`,
  `<b>Left lateral decubitus positioning</b> moves the gallbladder away from the duodenum and drops the liver into view — use it when supine images of the GB are suboptimal.`,
  `Don't anchor to your first impression. If a finding doesn't quite fit, scan more and consider alternatives. <b>Anchoring bias</b> is one of the most common diagnostic errors in ultrasound.`,
  `The best time to learn from a study is <b>right after</b> — pull up the report when it's dictated and compare what you saw to what the radiologist said. That loop closes faster than any textbook.`,
  `A calm, slow approach produces better images than rushing. <b>Breath-holding technique</b>: ask the patient to take a breath in, then breathe out halfway and hold. This positions organs optimally.`,
  `When you're not sure if something is real, <b>change your angle</b>. A true lesion is visible in multiple planes. An artifact or reverberation disappears when you rotate or heel-toe.`,
  `<b>Graded compression</b> for appendix evaluation: slowly displace bowel gas with steady probe pressure. The appendix is non-compressible when inflamed; normal bowel compresses easily.`,
  `If you find ascites unexpectedly, don't panic and don't ignore it. Assess the quantity, character, and look at the liver and spleen. Small amounts of free fluid can be physiologic in women mid-cycle.`,
  `Always correlate your ultrasound findings with the <b>clinical history</b>. A finding that's alarming in an asymptomatic patient may be expected in one with a known condition — and vice versa.`,
  `<b>Patient privacy</b> matters in ultrasound more than in most imaging — you're in close physical contact. Always explain before you scan, keep draping appropriate, and maintain professional boundaries.`,
  `When you're struggling to find a structure, <b>find something you know first</b>. The aorta is always midline. The liver is always right. Use landmarks to navigate.`,
  `If a study is truly non-diagnostic despite best efforts, say so clearly. A <b>non-diagnostic study honestly documented</b> is better than a falsely reassuring one with poor images.`,
  `<b>Fasting patients</b> are almost always easier to scan abdominally. When possible, confirm fasting status before starting — it saves time and improves your results significantly.`,
  `When a patient says "the last sonographer found something here" — scan that area extra carefully. Patient history is a form of clinical information. They may be right.`,
  `Learn the difference between <b>what you're asked to do</b> and <b>what you're seeing</b>. A patient sent for a renal study who has a large aortic aneurysm needs you to document both.`,
  `The hardest skill in ultrasound isn't knobology — it's knowing <b>when to stop and call for help</b>. Recognizing the limits of your own ability protects patients.`,
  `Ultrasound is operator-dependent, but that means it's also <b>operator-improvable</b>. Every scan is a chance to get better. The best sonographers never stop learning.`,
  `Trust your gut — but verify it. If something looks wrong, it probably is. Scan it from another angle, check the contralateral side, and <b>document your concern</b>.`,
  `<b>Ergonomics matter</b>. Sonographer injury rates are among the highest in healthcare. Adjust the bed height, use a neutral wrist, and switch hands when you can. Your career depends on it.`,
  `When asked by a patient "is everything okay?" — you are not the interpreter. Say: <b>"The radiologist will review the images and your doctor will discuss the results with you."</b> Every time.`,
  `The patient on the table doesn't care about your protocol. They're scared. A brief, human moment of <b>reassurance during setup</b> changes the entire exam dynamic.`,
  `After a difficult case, debrief — even just with yourself. What would you do differently? <b>Reflection after a hard scan</b> is how you convert experience into expertise.`,
  `<b>Ultrasound physics</b> isn't just for the registry. Understanding why your image looks the way it does helps you fix it faster than any preset ever could.`,
  `A great sonographer knows when to use the machine's help and when to rely on themselves. <b>Auto-presets are a starting point</b>, not a finishing point. Optimize every study manually.`,
  `Document incidental findings even if they're outside the scope of the order. A <b>missed incidental finding</b> that later becomes significant is a medicolegal and patient safety issue.`,
  `When the image is hard to read, ask yourself: "Is this because of the patient, my technique, or the machine?" <b>Troubleshooting starts with honest self-assessment.</b>`,
  `Ultrasound is a conversation between the probe and the patient's body. Learn to <b>listen to what the image is telling you</b> — not just look for what you expect to find.`,
  `The most important number on any Doppler study is the one that's <b>reproducible</b>. Take multiple samples, use the average, and document your technique. Outlier values mislead.`,
  `Never skip the <b>survey scan</b> before homing in on a specific structure. A quick sweep often reveals findings that change the priority of the entire examination.`,

  // ── FAST / Emergency / POCUS ───────────────────────────────────────────────
  `The FAST exam has <b>four windows</b>: right upper quadrant (Morrison's pouch), left upper quadrant (splenorenal), pelvic (pouch of Douglas / rectovesical), and pericardial. Miss one and you may miss the bleed.`,
  `In a trauma FAST, even a <b>thin sliver of free fluid</b> in Morrison's pouch can represent 200–400 mL of blood. It does not need to be a large pool to be significant.`,
  `The pericardial window in FAST: use the subxiphoid view. The heart should move freely inside the pericardial sac. A <b>dark rim</b> around the heart = effusion until proven otherwise.`,
  `For the splenorenal view in FAST, remember that blood collects <b>above the diaphragm</b> (pleural space) too. Always look superior to the spleen for anechoic pleural fluid.`,
  `Lung sliding on ultrasound rules out pneumothorax at that location. <b>Absent lung sliding</b> + absent B-lines + lung point = pneumothorax with high specificity.`,
  `B-lines in lung ultrasound are <b>vertical comet-tail artifacts</b> arising from the pleural line that erase A-lines and move with respiration. Three or more per field suggest interstitial fluid (pulmonary edema).`,
  `The <b>lung point</b> — the transition between sliding and non-sliding lung — is pathognomonic for pneumothorax. Slide along the chest wall until you find where sliding starts and stops.`,
  `For bladder volume estimation: <b>length × width × height × 0.72</b>. Useful in POCUS settings to confirm urinary retention before catheterization.`,
  `In septic shock, IVC collapsibility > <b>50%</b> with respiration in a spontaneously breathing patient suggests volume responsiveness — a fluid bolus is likely to help.`,
  `The <b>eFAST</b> (extended FAST) adds lung windows to the standard four FAST views. It adds 5–10 minutes but significantly improves detection of pneumothorax and hemothorax in trauma.`,
  `Pleural effusion on ultrasound: anechoic fluid above the diaphragm with <b>atelectatic lung floating</b> inside it (the "jellyfish sign"). Complex or echogenic fluid = exudate, empyema, or hemothorax.`,
  `When scanning for the appendix, the <b>blind-end tip</b> of the appendix confirms you've found the true appendix and not a loop of bowel. An appendix > 6 mm outer diameter is abnormal.`,
  `POCUS for DVT in the ICU: compress the <b>common femoral and popliteal veins</b>. A two-point compression exam misses only ~5% of DVTs and can be done at the bedside in under 5 minutes.`,
  `In cardiac arrest, use the subxiphoid view during pulse check. <b>Absence of cardiac motion</b> (asystole) vs. fine ventricular fibrillation or PEA with motion changes resuscitation decisions.`,
  `Gallbladder ultrasound for cholecystitis: <b>gallstones + wall thickening + sonographic Murphy's sign</b> = high specificity for acute cholecystitis. You need all three for confidence.`,
  `Abdominal aorta POCUS: measure in the <b>transverse plane</b> at the level of the umbilicus. An aorta > 3 cm is aneurysmal by definition. > 5.5 cm is typically surgical.`,

  // ── Pediatric Ultrasound ───────────────────────────────────────────────────
  `In pediatric ultrasound, <b>high frequency probes</b> (7–15 MHz) are preferred for most structures due to smaller body habitus and shallower target depths. Always start high.`,
  `Pyloric stenosis: measure the pyloric channel length (<b>> 17 mm</b>) and muscle thickness (> 3 mm) in the transverse view. The "target sign" and "cervix sign" are the classic appearances.`,
  `Intussusception: the <b>"donut sign"</b> or "target sign" in transverse — bowel within bowel. Found most commonly in the right lower quadrant. Always use color Doppler to assess viability.`,
  `The neonatal hip ultrasound (Graf method) measures the <b>alpha angle</b> (acetabular roof angle) and beta angle. Alpha > 60° = normal. < 50° = dysplastic. Perform before 4–6 months of age.`,
  `In a neonate, the <b>anterior fontanelle</b> provides a natural acoustic window for brain ultrasound. Use it before closure (typically 9–18 months) to evaluate for IVH, hydrocephalus, and periventricular leukomalacia.`,
  `Grade the IVH (intraventricular hemorrhage) in neonates: <b>Grade I</b> = germinal matrix only, <b>Grade II</b> = IVH without ventricular dilatation, <b>Grade III</b> = IVH with dilatation, <b>Grade IV</b> = parenchymal involvement.`,
  `Pediatric kidneys are relatively larger compared to body size than adult kidneys. Use <b>age-adjusted nomograms</b> — a 5 cm kidney in a 2-year-old is normal; in a 10-year-old, it may be small.`,
  `For pediatric appendicitis, the appendix is often more mobile than in adults. Start at the <b>iliac vessels</b> as a landmark and trace the cecum inferiorly to find the appendix.`,
  `In a child with a scrotal mass, think differently than in adults — <b>testicular torsion</b> is far more common in the pediatric age group than in adults. The "bell clapper deformity" is the underlying anatomic cause.`,
  `The pediatric spleen is proportionally larger than the adult spleen. <b>Splenomegaly</b> in a child with fever — think mono (EBV), CMV, or malaria before assuming portal hypertension.`,

  // ── Vascular Access & Interventional ──────────────────────────────────────
  `Ultrasound-guided IV access: use the <b>short-axis (transverse) view</b> to confirm needle tip position in the vessel before threading the catheter. In-plane (long-axis) shows the full needle but requires more skill.`,
  `For ultrasound-guided central line placement, confirm <b>venous vs. arterial</b> access before dilating: vein is compressible, pulsatile flow on Doppler is arterial. Don't rely on blood color alone.`,
  `Always scan the vein <b>before</b> placing a central line — confirm patency, size, and absence of existing thrombus. A thrombosed internal jugular is a contraindication to cannulation there.`,
  `After placing a central line, perform a quick lung ultrasound to rule out <b>pneumothorax</b>. It's faster, more sensitive, and can be done immediately — no need to wait for a chest X-ray.`,
  `Arteriovenous fistula maturation criteria: <b>flow > 600 mL/min</b>, vein diameter > 6 mm, depth < 6 mm, straight segment > 10 cm. All four should be met before cannulation.`,
  `When mapping for PICC line placement, identify the <b>basilic vein</b> in the upper arm — it's the preferred site for PICC insertion due to its size and straight course. Measure diameter and depth.`,
  `Pseudoaneurysm after arterial puncture: a <b>to-and-fro flow pattern</b> ("yin-yang sign") within a pulsatile mass adjacent to the artery. Confirm the neck connecting it to the artery before treatment.`,
  `Ultrasound-guided thoracentesis: identify the effusion, mark the superior border of the rib (to avoid the neurovascular bundle running below each rib), and insert <b>above the rib</b>.`,

  // ── Doppler Physics Deep Dives ─────────────────────────────────────────────
  `The <b>Doppler equation</b>: f_d = 2 × f_0 × v × cos θ / c. The cosine of the angle is the key variable — at 60°, cos θ = 0.5, meaning you only measure half the true velocity.`,
  `<b>Continuous wave (CW) Doppler</b> has no range resolution but no aliasing. Use it for high-velocity jets (aortic stenosis, TR) where pulsed wave would alias.`,
  `<b>Pulsed wave (PW) Doppler</b> has range resolution (you pick the sample gate location) but is limited by the Nyquist limit. Best for low-to-moderate velocity vessels.`,
  `The <b>resistive index (RI)</b> = (PSV − EDV) / PSV. It reflects downstream resistance and is independent of angle correction since it's a ratio. Normal renal RI < 0.70.`,
  `The <b>pulsatility index (PI)</b> = (PSV − EDV) / mean velocity. PI is more sensitive to mild increases in resistance than RI and is preferred in obstetric Doppler (umbilical artery, MCA).`,
  `<b>Middle cerebral artery (MCA) PSV</b> is used in fetal anemia surveillance. MCA PSV > <b>1.5 MoM</b> (multiples of the median) for gestational age warrants amniocentesis or transfusion consideration.`,
  `The <b>sample volume (gate size)</b> in PW Doppler should be placed in the center of the vessel and sized to about <b>2/3 of the vessel lumen</b>. Too large = wall thump; too small = misses peak velocity.`,
  `<b>Spectral broadening</b> — filling in of the spectral window below the peak — indicates turbulence. Mild broadening is normal in tortuous vessels; severe broadening suggests stenosis or post-stenotic flow.`,
  `The <b>systolic window</b> (clear space below the systolic peak in normal laminar flow) disappears with turbulence. Loss of the systolic window on its own is a sign of flow disturbance, not necessarily stenosis.`,

  // ── Specialty Protocols ────────────────────────────────────────────────────
  `For a <b>renal ultrasound</b>, always document both kidneys in long and transverse axes, the collecting system, and bladder — even if the order only asks for one kidney. Bilateral disease is common.`,
  `During a <b>liver ultrasound</b>, use multiple planes to evaluate all 8 Couinaud segments. The right lobe segments (V–VIII) are accessed intercostally; the left lobe (II–IV) and caudate (I) subcostally.`,
  `The <b>hepatic artery</b> is part of the porta hepatis triad with the portal vein and common bile duct. Always document hepatic artery flow direction (hepatopetal) and waveform in liver transplant surveillance.`,
  `For a <b>scrotal ultrasound</b>, start with gray-scale to assess echotexture, then add color Doppler. Always document both testes and epididymides, even if the question is unilateral.`,
  `A complete <b>pelvic ultrasound</b> includes transabdominal AND transvaginal components. The TV probe gives better resolution of the endometrium, ovaries, and adnexa — never skip it in non-pregnant women.`,
  `For a <b>carotid duplex</b>, sample the CCA proximally, mid, and distally. Then the ICA proximally (most stenoses occur at the origin), and the ECA. Don't forget the vertebral artery bilaterally.`,
  `During a <b>lower extremity arterial</b> study, document every segment: iliac (if visible), CFA, SFA proximal/mid/distal, popliteal, and trifurcation vessels. A segmental approach localizes disease accurately.`,
  `For a <b>venous insufficiency</b> study, evaluate both superficial (GSV, SSV) and deep systems for reflux. Use augmentation and Valsalva. Document the saphenofemoral and saphenopopliteal junctions.`,
  `In a <b>fetal anatomy survey</b>, follow the same order every time. Head → face → spine → chest → heart → abdomen → kidneys → extremities → placenta → fluid → cord. Consistency prevents omissions.`,
  `A <b>first-trimester screen</b> includes NT measurement, nasal bone, ductus venosus Doppler, and tricuspid regurgitation assessment. Each adds incremental sensitivity for aneuploidy detection.`,

  // ── Advanced Tips ──────────────────────────────────────────────────────────
  `<b>Strain imaging</b> (speckle tracking) quantifies myocardial deformation. Global longitudinal strain (GLS) < −20% is normal; values closer to zero indicate subclinical dysfunction before EF drops.`,
  `<b>Contrast-enhanced ultrasound (CEUS)</b> uses microbubble agents to characterize liver lesions in real-time. It avoids radiation and is superior to CT for some lesion types in experienced hands.`,
  `<b>Elastography</b> measures tissue stiffness. In the liver, shear wave values < 7 kPa suggest no significant fibrosis; > 12–13 kPa suggests cirrhosis. It's increasingly replacing liver biopsy for staging.`,
  `<b>3D/4D ultrasound</b> adds volume acquisition. Most valuable in fetal anomaly assessment, uterine anomaly characterization, and guiding complex interventional procedures.`,
  `In fetal echo, <b>tissue Doppler imaging</b> of the fetal myocardium can detect subtle cardiac dysfunction in IUGR and diabetic pregnancies before changes appear on conventional imaging.`,
  `The <b>Doppler gate</b> should always be positioned distal to a stenosis to capture the peak velocity jet. Placing the gate proximal gives pre-stenotic velocities and underestimates severity.`,
  `<b>High frame rate ultrasound</b> (plane wave imaging) allows real-time shear wave visualization and ultra-fast cardiac imaging. It's emerging in clinical vascular and cardiac research settings.`,
  `<b>Fusion imaging</b> overlays real-time ultrasound with prior CT or MRI. Invaluable for targeting lesions that are visible on cross-sectional imaging but not clearly seen on B-mode alone.`,
  `When the clinical question requires it, <b>standing position</b> during scrotal or venous insufficiency scanning reveals findings (varicocele grade, reflux) that aren't apparent when supine.`,

  // ── Career & Professionalism ───────────────────────────────────────────────
  `Your registry (ARDMS, CCI, ARRT) isn't just a credential — it's your clinical credibility. Keep your <b>CME current</b>, and always scan within your verified competency scope.`,
  `<b>Seek out a mentor</b> in your first year. The gap between what school teaches and what the real scanner requires is filled by experienced sonographers who are willing to share.`,
  `The <b>sonographer shortage</b> is real — experienced techs are valuable. Protect your value by specializing, cross-training, or earning additional credentials in a second modality.`,
  `<b>Burnout</b> in sonography is linked to high scan volume, repetitive motion, and patient-facing emotional demands. Know the signs: apathy, cynicism, physical pain. Act before it becomes chronic.`,
  `When you disagree with a radiologist's interpretation, the professional approach is to <b>document what you saw</b>, communicate your concern through proper channels, and move on. Never alter images.`,
  `Floating (per diem) can expose you to <b>different machines, protocols, and patient populations</b> faster than staying in one department. Early in your career, variety accelerates growth.`,
  `<b>Travel sonography</b> pays 30–50% more than staff positions but requires rapid adaptation. Before going travel, build at least 1–2 years of solid staff experience in your primary modality.`,
  `Your technique is your fingerprint. <b>Radiologists notice</b> when image quality drops. Consistently excellent images build your reputation — consistently poor ones follow you.`,
  `Always greet your patient by name, introduce yourself, and explain what you're about to do. <b>Patient experience scores</b> affect department funding and your professional reputation.`,
  `Keep a <b>logbook</b> of unusual findings or cases you want to learn more about. After one year you'll have a personal reference of rare pathology that no textbook can replicate.`,
  `Invest in a quality <b>ergonomic setup</b> early: adjustable bed, padded armrest, neutral wrist position. Rotator cuff injuries and carpal tunnel end careers prematurely. Prevention is cheaper than surgery.`,
  `Cross-training in a second modality (echo if you do vascular, OB if you do general) makes you <b>more competitive, more hirable, and more resilient</b> to department restructuring.`,
  `When you start a new job, spend the first 30 days <b>listening more than talking</b>. Learn the culture, the radiologists' preferences, and the unwritten protocols before suggesting changes.`,
  `The ARDMS SPI (Sonography Principles and Instrumentation) exam tests physics that every sonographer uses every day. <b>Mastering physics</b> makes you better at the machine, not just better at the registry.`,
  `<b>Peer review</b> — having a colleague or radiologist review your images — is one of the fastest ways to improve. Ask for it. It takes humility, but it compounds.`,
  `Document your <b>continuing education</b> in a folder throughout the year. When renewal time comes, you'll thank yourself. Audit risk is real and scrambling to find 30 CMEs is avoidable.`,
  `In every department you work in, introduce yourself to the <b>interpreting radiologists</b> by name. Sonographers who build those relationships get faster reads, better feedback, and more clinical respect.`,
  `The best sonographers I've worked with share one trait: they are <b>genuinely curious</b> about what they see. Curiosity drives the extra angle, the extra Doppler gate, the call to the radiologist.`,
  `When a scan is negative, that is still a <b>clinical result</b>. "No DVT identified" or "no gallstones" changes patient management. A negative study done well is as valuable as a positive one.`,
  `Develop a <b>pre-scan ritual</b>: review the order, check prior images, verify patient identity. Thirty seconds of preparation prevents minutes of re-scanning and potential errors.`,
  `The scan room is your domain. Keep it <b>clean, stocked, and organized</b>. A well-prepared room reflects a well-prepared sonographer and sets the right tone for every patient interaction.`,
  `<b>Read the radiologist's reports</b> on your cases. Not just to check if they agreed — but to learn the clinical language they use. Adopt that language in your own communication.`,
  `Ultrasound is uniquely personal — you are physically present with the patient in ways other imaging modalities aren't. <b>The human element</b> of sonography is a privilege. Honor it.`,

  // ── Additional Vascular & Hemodynamics ─────────────────────────────────────
  `The <b>vertebral arteries</b> should be evaluated bilaterally at the same level (typically V2 segment between C4–C6). Asymmetry in diameter or velocity > 30% between sides is significant.`,
  `<b>Intimal-medial thickness (IMT)</b> of the CCA is a marker of subclinical atherosclerosis. Normal IMT is < 0.9 mm. Values > 1.0 mm are associated with increased cardiovascular risk.`,
  `When the ICA is occluded, the ECA may provide collateral flow to the brain via the <b>ophthalmic artery</b>. You may see reversed or bidirectional flow in the periorbital vessels — document it.`,
  `A <b>high-resistance ICA waveform</b> (sharp systolic peak, absent diastole) in a patient with known carotid disease suggests severe distal disease or occlusion. The brain isn't receiving enough flow.`,
  `For mesenteric ischemia evaluation, the <b>SMA peak systolic velocity > 275 cm/s</b> or EDV > 45 cm/s are the primary duplex thresholds for hemodynamically significant stenosis.`,
  `The <b>celiac artery</b> can be compressed by the median arcuate ligament — velocities drop with expiration and rise with inspiration in MALS. This positional change is diagnostic.`,
  `Always document <b>waveform morphology bilaterally</b> during upper extremity arterial studies. Side-to-side pressure difference > 15 mmHg or waveform asymmetry suggests subclavian or axillary disease.`,
  `In the post-thrombotic syndrome, venous valves are damaged. Reflux and obstruction often coexist. Always <b>document both</b> — reflux alone vs. combined disease changes management.`,
  `The <b>great saphenous vein (GSV)</b> runs medially from the ankle to the saphenofemoral junction in the groin. The small saphenous vein (SSV) runs posteriorly to the saphenopopliteal junction behind the knee.`,
  `For renal vein thrombosis, the renal vein will show <b>absent flow or echogenic thrombus</b>. The renal artery RI increases dramatically due to venous hypertension — RI > 0.90 is expected.`,

  // ── Additional OB/GYN ──────────────────────────────────────────────────────
  `The <b>ductus venosus</b> waveform shows a and S/D waves. Absent or reversed A-wave (during atrial contraction) is a marker of fetal compromise — correlate with umbilical artery Doppler and biophysical profile.`,
  `<b>Dichorionic-diamniotic (DCDA)</b> twins have two placentas and two sacs — the lambda (twin peak) sign is seen at the membrane insertion. MCDA twins have one placenta and the T-sign at the membrane.`,
  `In <b>MCDA twins</b>, scan every 2 weeks from 16 weeks to monitor for twin-to-twin transfusion syndrome (TTTS). Polyhydramnios in one sac + oligohydramnios in the other = Quintero staging needed.`,
  `Endometriosis on ultrasound: look for <b>homogeneous low-level internal echoes</b> ("ground glass") in ovarian cysts (endometriomas). Bilateral ovarian cysts in a woman with dysmenorrhea = high suspicion.`,
  `The <b>arcuate uterus</b> is a normal variant — a small myometrial indentation at the fundus < 1 cm. It's not associated with adverse pregnancy outcomes and does not require treatment.`,
  `Fibroids are the most common pelvic mass in women of reproductive age. Classify by location: <b>submucosal</b> (distort the cavity), intramural (in the wall), subserosal (project outward).`,
  `A <b>heterogeneous uterine mass</b> with increased vascularity and irregular margins in a perimenopausal or postmenopausal woman should raise concern for endometrial carcinoma. Measure the endometrium.`,
  `For infertility workups, document <b>antral follicle count (AFC)</b> — count all follicles 2–10 mm in each ovary on day 3 of the cycle. Total AFC < 5–7 suggests diminished ovarian reserve.`,
  `<b>Ovarian hyperstimulation syndrome (OHSS)</b> after fertility treatment: massively enlarged ovaries with multiple follicles and ascites. Document ovarian size and fluid volume — it guides clinical management.`,
  `The fetal <b>biophysical profile (BPP)</b> scores five parameters: fetal tone, movement, breathing, AFI, and NST. Each scores 2 (present) or 0 (absent). A score of 8–10 is reassuring; ≤ 6 needs urgent review.`,

  // ── Additional Echo & Cardiac ──────────────────────────────────────────────
  `In <b>dilated cardiomyopathy</b>, the LV is globally dilated and poorly contracting. The mitral valve may show functional regurgitation due to annular dilatation. EF is typically < 40%.`,
  `<b>Stress echocardiography</b> uses exercise or dobutamine to provoke wall motion abnormalities. New or worsening wall motion abnormality = ischemia. Requires careful baseline documentation at each wall segment.`,
  `The <b>proximal isovelocity surface area (PISA)</b> method quantifies mitral regurgitation severity. Shell radius > 1 cm at 40 cm/s aliasing = at least moderate MR. Learn the formula for your lab.`,
  `In <b>cardiac tamponade</b>, look for: RA systolic collapse, RV diastolic collapse, IVC plethora (> 2.1 cm, < 50% collapse), and respiratory variation in mitral/tricuspid inflow > 25%.`,
  `<b>Constrictive pericarditis</b> vs. restrictive cardiomyopathy: both show E/A > 2 and short deceleration time. Constriction shows annulus reversus (septal e' > lateral e') and septal bounce on M-mode.`,
  `The <b>right ventricle</b> is load-dependent. An RV that looks normal at rest may be severely dysfunctional under stress. Always assess RV in the context of clinical context — heart rate, preload, and afterload.`,
  `<b>Bicuspid aortic valve</b>: look for two cusps (vs. three) on the parasternal short-axis view. Associated with aortic dilatation and coarctation — always measure the aortic root and ascending aorta.`,
  `Endocarditis: look for <b>vegetations</b> on valve leaflets — mobile, irregular, echogenic masses. The mitral and aortic valves are most commonly affected. Always use multiple views and document mobility.`,
  `The <b>E/e' ratio</b> (mitral inflow E velocity / tissue Doppler e' velocity) estimates LV filling pressures. E/e' > 14 suggests elevated filling pressures (diastolic dysfunction with raised PCWP).`,
  `<b>Right ventricular pressure</b> can be estimated without TR: use the RVSP from TR + estimated RAP, or estimate from PA acceleration time. PA AT < 100 ms suggests pulmonary hypertension.`,

  // ── Final Clinical Pearls ──────────────────────────────────────────────────
  `When starting out, pick <b>one modality and master it</b> before adding others. Depth in one area compounds into expertise faster than surface knowledge in five.`,
  `The best scan report has three qualities: it's <b>accurate, complete, and actionable</b>. If the ordering provider can't decide what to do next after reading your images, the study didn't fully serve the patient.`,
  `<b>Ultrasound can be wrong</b> — and knowing when to say "correlate with CT or MRI" is a skill, not a weakness. Use the right tool for the right question.`,
  `Every patient deserves the same level of technical effort regardless of body habitus, cooperation, or how many patients are waiting. <b>Technical quality is an ethical standard</b>, not just a professional one.`,
  `<b>Measure twice, document once.</b> Taking an extra 30 seconds to confirm a borderline measurement saves the patient a repeat study and saves you a quality flag.`,
  `The day you stop being nervous about missing something is the day to be most careful. <b>Appropriate clinical anxiety</b> keeps your standards high. Overconfidence causes misses.`,
  `Learn to read your own prior studies before rescanning. "Compared to prior" is one of the most valuable phrases in radiology — and you can only use it if you look at what came before.`,
  `<b>Incidental findings</b> are one of the most ethically complex parts of sonography. You saw it, you documented it — now the radiologist and ordering provider must act. Do your part and document clearly.`,
  `In any imaging modality, the history you're given shapes what you look for. But the best sonographers look at <b>everything</b> — not just what the order requests. Real findings don't read the requisition.`,
  `<b>You are part of the diagnostic team.</b> The radiologist interprets, the physician decides, but the images you create are the foundation. Take pride in the craftsmanship of every frame you save.`,
  `The <b>common femoral artery</b> bifurcates into the SFA and profunda femoris typically 3–5 cm below the inguinal ligament. Document the bifurcation level — it matters for surgical planning.`,
  `<b>Hepatic steatosis grading</b> on ultrasound: mild = slightly increased echogenicity, vessel walls still visible; moderate = vessels less defined; severe = markedly echogenic liver, posterior attenuation, poor diaphragm visualization.`,
  `The <b>resistive index</b> is falsely elevated in tachycardia and falsely low in bradycardia. Always note heart rate when reporting renal or transplant RIs — context prevents misinterpretation.`,
  `A <b>complex renal cyst</b> (Bosniak IIF, III, or IV) needs follow-up or surgical consideration. Simple cysts (Bosniak I) require no further workup. Know your Bosniak categories — they drive clinical decisions.`,
  `<b>Scrotal pearl</b>: a loose body in the scrotal sac — a calcified, mobile, extratesticular nodule. It's benign and often found incidentally. Don't mistake it for a calcified testicular mass.`,
  `Fetal <b>echogenic bowel</b> (as bright as bone) is associated with cystic fibrosis, chromosomal anomalies, CMV infection, and swallowed blood. Grade 2–3 echogenic bowel warrants genetic counseling discussion.`,
  `The <b>normal thymus</b> in a neonate appears as a homogeneous, slightly hyperechoic structure in the anterior mediastinum — it can mimic a mass. It has a characteristic lobulated shape and moves with swallowing.`,
  `For <b>venous mapping</b> before CABG, document both the GSV and basilic vein from groin/axilla to ankle/wrist. Surgeons need diameter (≥ 2.5 mm), depth (< 6 mm preferred), compressibility, and length of usable segment.`,
  `<b>Mirror image artifact</b> at the aorta: structures anterior to the aorta can appear to be duplicated posterior to it. This is an artifact — confirm by changing probe angle and looking for it to shift or disappear.`,
  `When you finish a difficult scan, take 60 seconds before the next patient to <b>reset mentally</b>. The patient who just left deserves your full attention. So does the one walking in.`,
];

/** Returns today's tip (same for the full day, changes at midnight UTC) */
export function getDailyTip(): string {
  const dayIndex = Math.floor(Date.now() / 86_400_000);
  return SONO_TIPS[dayIndex % SONO_TIPS.length];
}
